# Generated by Django 5.1.3 on 2025-02-15 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_description', models.TextField()),
                ('shipment_date', models.DateField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentApp.consignee')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentApp.consignor')),
            ],
        ),
    ]
