# Generated by Django 5.1.3 on 2025-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
