# Generated by Django 5.1.3 on 2025-02-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0002_consignor_total_quantity_shipment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
