# Generated by Django 5.1.3 on 2025-02-17 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0004_remove_consignor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='ShipmentApp.consignor'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
