# Generated by Django 5.1.6 on 2025-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0005_consignor_updated_at_shipment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('warehouse', 'In Warehouse'), ('transit', 'In Transit')], default='warehouse', max_length=10),
        ),
    ]
