# Generated by Django 5.1.6 on 2025-02-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0006_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
