# Generated by Django 5.1.6 on 2025-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0007_alter_consignor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
