# Generated by Django 5.1.6 on 2025-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0009_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('warehouse', 'In Warehouse'), ('transit', 'In Transit')], default='warehouse', max_length=10),
        ),
    ]
