# Generated by Django 5.1.6 on 2025-02-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0010_alter_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='is_delivered',
        ),
    ]
