# Generated by Django 5.1.6 on 2025-02-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentApp', '0012_consignor_ticket_number_shipment_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
